// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiNqTj-yrj5uUH1oSbVMkGPYOK8WHHG9s',
    appId: '1:811220109761:web:dbc8c4c9c679435efec740',
    messagingSenderId: '811220109761',
    projectId: 'ballast-test',
    authDomain: 'ballast-test.firebaseapp.com',
    storageBucket: 'ballast-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZBNrIPCV_6LzU9WO0xIcf549PeRBRyCE',
    appId: '1:811220109761:android:9316afb10cf9b302fec740',
    messagingSenderId: '811220109761',
    projectId: 'ballast-test',
    storageBucket: 'ballast-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd9QcV5Cg2qLI5kw_lJYBqNY0jpZry5tQ',
    appId: '1:811220109761:ios:c5eb9c5d3f5380e0fec740',
    messagingSenderId: '811220109761',
    projectId: 'ballast-test',
    storageBucket: 'ballast-test.appspot.com',
    iosBundleId: 'com.example.ballastTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd9QcV5Cg2qLI5kw_lJYBqNY0jpZry5tQ',
    appId: '1:811220109761:ios:c5eb9c5d3f5380e0fec740',
    messagingSenderId: '811220109761',
    projectId: 'ballast-test',
    storageBucket: 'ballast-test.appspot.com',
    iosBundleId: 'com.example.ballastTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiNqTj-yrj5uUH1oSbVMkGPYOK8WHHG9s',
    appId: '1:811220109761:web:5ce2002142a0b68dfec740',
    messagingSenderId: '811220109761',
    projectId: 'ballast-test',
    authDomain: 'ballast-test.firebaseapp.com',
    storageBucket: 'ballast-test.appspot.com',
  );
}
